### ISSUE TITLE
puppet_gem provider broken on Fedora

### ISSUE THREAD

**Issue by antoineco** [puppet-community/puppet-archive#103]
Fedora packages do not install Puppet 4 in /opt but in standard OS paths, and rely on the OS Ruby instead of letting Puppet ship its own Ruby.

As a result the `puppet_gem` provider set in [params.pp](https://github.com/puppet-community/puppet-archive/blob/master/manifests/params.pp#L23) will not work because the [gem executable path set upstream](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/package/puppet_gem.rb#L15) does not exist.

I open this issue as a proposal to send a PR which fixes this. If supporting Fedora is not desired feel free to close the issue.

**Comment by igalic** [comment]
:+1:
