### ISSUE TITLE
Query string breaks file:// behavior

### ISSUE THREAD

**Issue by jairojunior** [puppet-community/puppet-archive#56]
Query string is currently hardcoded in url_path, but it breaks file:// behavior cause '?' (question mark) is a valid character for file names.     

I managed to work in a simple fix, but I think each implementation (HTTP, FTP, File) should receive an URI and handle its own internal behavior (include or not a query string). What do you think?

We'll also need tests for this...

**Comment by jairojunior** [comment]
@nanliu Can you verify PR #57?

**Comment by nanliu** [comment]
I'll review it today.

**Comment by nanliu** [comment]
Close #57
