### ISSUE TITLE
Remove the dependency on Faraday

### ISSUE THREAD

**Issue by hajee** [puppet-community/puppet-archive#60]
For our use case it is difficult to get an extra gem installed. At the moment, this means we cannot use the module. I would like to use at least the types (and providers) in this module, but they are 'hard wired' using faraday.

I've looked at the code and it seems you are using faraday mostly as an easy way to call NET:HTTP. I could try and make a PR removing Faraday from the provider. Is this beneficial? Am I missing something in the reasoning for Faraday?

**Comment by nanliu** [comment]
We can remove faraday once we implement a proper redirect:
https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/follow_redirects.rb

**Comment by hajee** [comment]
In older issues I saw you also had ideas to remove faraday. Did you start with this?

**Comment by nanliu** [comment]
I started working on #55, but got hanged up because of the redirect issue.

**Comment by jairojunior** [comment]
+1

**Comment by hajee** [comment]
I've been looking into this. I'm guessing issue #55 is caused by the standard `Net::HTTP` class and not by Faraday. It looks like `Net::HTTP`   is reading the whole response object into memory, causing memory problems when working with big files. So when we replace Faraday by our own solution, we also have to be careful not to keep the same problem.

Wouldn't it be easier to use `wget`. This would still introduce a dependency, but this is a rpm dependency that, most of the times is much easier. The advantage would be a battle tested en tried `http`/`ftp` and `https` implementation.

It supports a lot of stuff, for example:
- retries
- limit rate. This could be useful when downloading files on fragile networks
- proxies
- redirects

**Comment by nanliu** [comment]
This module was originally written to handle both windows/linux. A native ruby solution worked better than being dependent on a package that I could not install in windows. Both wget/curl can be implemented as providers to supplement the default provider (or even default providers on Linux). The util portion can be moved to download method so the default provider can be the parent provider with the download method replaced with your preferred solution on platforms where it's suitable.

**Comment by hajee** [comment]
Sorry. Forgot about Windows for a moment ;-). I'll have my stab at making a provider for unix wget.
