### ISSUE TITLE
Follow redirect using curl

### ISSUE THREAD

**Issue by thiagomarinho** [puppet-community/puppet-archive#65]
I needed curl to follow redirects, with -L parameter, i.e.:

```
curl http://google.com.br/ -o google.html
```
gets the wrong file, while:

```
curl http://google.com.br/ -L -o google.html
```
gets the actual index file.

Do you agree that the curl provider should work this way, following redirects? I made the changes on my fork but I want to know what do you think about it before making a pull request.

**Comment by jairojunior** [comment]
+1

I think @hajee was responsible for curl support. Do you have any comments?

**Comment by hajee** [comment]
Does it need to be default behaviour, or do we need a special parameter to enable this behaviour?

**Comment by jairojunior** [comment]
@hajee I think it should be a default behavior since faraday defaults to follow redirects.
