### ISSUE TITLE
Make faraday package install optional

### ISSUE THREAD

**Issue by robinbowes** [puppet-community/puppet-archive#68]
Or support installation of different package names with other providers (eg. pe-rubygem-faraday using the default yum provider on EL platforms).

Our puppet masters don't have internet access and so can't install gems. We generally package gems into RPMs using fpm and install them from an internal repo.

I'll try and send in a Pr to implement these changes, if I get chance next week

**Comment by eperdeme** [comment]
I hit the same issues with a puppet apply today.

**Comment by robinbowes** [comment]
I would favour the addition of a flag to turn off the installation of the gems by the modules, so the user can install them in whatever way they wish, and use dependencies/chaining to make sure the gems are installed before the module use used.

**Comment by nanliu** [comment]
So the gems are not installed until the class archive is included, so isn't the installation optional as is? I don't see the archive class included by any define type. I'm not opposed to a patch, just want to understand where this causing an issue in the existing code.

**Comment by robinbowes** [comment]
You're right. If I don't include the archive module the gems don't get installed, so I can just write a separate class that installs the gems from RPM or however I want.

I guess this is a non-issue then.
