### ISSUE TITLE
Unable to obtain file via archive::nexus with Puppet 4

### ISSUE THREAD

**Issue by smbambling** [puppet-community/puppet-archive#70]
Just to note this works correctly on Puppet 3.x.

This seems to have something to do with the faraday_middleware and the checksum that the archive::nexus calls for the archive type.

If you comment out the checksum_url and checksum_type parameters your able to successfully obtain the file from a nexus store.

I've checked and the two variables for urls are generating valid urls that I can manually download both the file and the checksum (md5) file.

````
$artifact_url = assemble_nexus_url($url, delete_undef_values($query_params))
$checksum_url = regsubst($artifact_url, "p=${packaging}", "p=${packaging}.${checksum_type}")
````

On a vagrant instance with Puppet 4 I have the following gems installed

````
# gem list

*** LOCAL GEMS ***

faraday (0.9.1)
faraday_middleware (0.10.0)
json (1.8.3)
multipart-post (2.0.0)
````

On a host with Puppet 3 installed the only difference seems to be the version of the json gem is 1.5.5, but i've even downgraded that gem and still get the same issue.

**Comment by nanliu** [comment]
I'm guessing this is related to the AIO packaging, and maybe the AIO gem v.s. system gem. FYI, I'll be offline for a while so will not be able to respond or provide further feedback.

**Comment by smbambling** [comment]
I'll keep trying to dig and do some testing for the time being I've set the $checksum_type to none to effectively disable the checking as a work around for anyone else having this issue

**Comment by smbambling** [comment]
Fixed with merge of 70
