### ISSUE TITLE
should staging be a dependency?

### ISSUE THREAD

**Issue by logicminds** [puppet-community/puppet-archive#73]
Looking at https://github.com/puppet-community/puppet-archive/blob/master/manifests/params.pp#L13
I see that the params is expecting the variable to resolve.  However since I don't have the staging module the variable is blank.  Should the dependency be listed in metadata, and fixtures?

**Comment by logicminds** [comment]
The work around would be to set a top scope variable with the same name.

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-staging/blob/master/lib/facter/staging_windir.rb seems to be the fact. Could port it in as archive_windir, or something. I think depending on staging is not the right solution.

**Comment by logicminds** [comment]
I am inclined to just replace it with 'c:\\windows\\Temp'

**Comment by nanliu** [comment]
yeah, the existing fact should be replicated and renamed since C:\Windows isn't always the windows directory or system drive.
