### ISSUE TITLE
ensure directory exists before moving archive

### ISSUE THREAD

**Issue by logicminds** [puppet-community/puppet-archive#74]
When moving the archive after download we should create the directory structure so that the mv function does not fail.

https://github.com/puppet-community/puppet-archive/blob/0.3.0/lib/puppet/provider/archive/default.rb#L66

This can be fixed by inserting the following before the line above `    FileUtils.mkdir_p(File.dirname(archive_filepath))
`

I would issue a PR but since the next version is under a major refactor I was not sure if we wanted to create a 0.3.1 version.

**Comment by jyaworski** [comment]
Hello.

Is this still relevant? The file in question doesn't seem to exist any more. I believe I may have fixed it with #89. Can you confirm?

**Comment by nanliu** [comment]
Closed per #95.
