### ISSUE TITLE
Release 0.4.x to puppet-community namespace on forge

### ISSUE THREAD

**Issue by mkrakowitzer** [puppet-community/puppet-archive#75]
This module does not have a release on the forge. Can I go ahead and do this?

If we are happy to do this, @nanliu could you deprecate nanliu/archive with a 999.999.999 release?

**Comment by nanliu** [comment]
Sure release a version to forge. Anything I need to note in the final release? is 999.999.999 the process to deprecate? Or are we just leaving it alone like: https://forge.puppetlabs.com/joshcooper/powershell

**Comment by mkrakowitzer** [comment]
Officially this is the process:

**Comment by jyaworski** [comment]
This seems to be an issue with puppet-community modules at large. I know at least https://github.com/puppet-community/puppet-rundeck/issues/131 is related to releasing this module on the forge.

**Comment by walterheck** [comment]
@mkrakowitzer yes, I would also love to see this on the forge, makes r10k's Puppetfile look a bit nicer :)

**Comment by igalic** [comment]
currently struggling with travis: https://github.com/maestrodev/puppet-blacksmith/issues/23

**Comment by rnelson0** [comment]
puppet/archive 0.4.4 is now available at https://forge.puppetlabs.com/puppet/archive rather than your favorite 404!

**Comment by rnelson0** [comment]
I think we just need a 999.999.999 release from @nanliu before closing this out.

**Comment by nanliu** [comment]
Done, see https://forge.puppetlabs.com/nanliu/archive/999.999.999.
